### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by gunner786** [ajay2507/TravelWebApplication#3]
I am getting an error for creating connection pool

my "application.properties"

server.port=${port:8181}
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/travel
spring.datasource.username=root
spring.datasource.password=Mesut@2610
spring.datasource.ssl
spring.jpa.show-sql=true

Please let me know how to get rid of this ...

**Comment by pajaydev** [comment]
@gunner786  I think it can't able to connect to your datasource, I would recommend to check connecting via command prompt.
